// <auto-generated />
using Backend.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Backend.Migrations
{
    [DbContext(typeof(TavernContext))]
    partial class TavernContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Backend.Models.Booze", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<int?>("TavernID");

                    b.Property<string>("TypeOfBooze");

                    b.HasKey("ID");

                    b.HasIndex("TavernID");

                    b.ToTable("Booze");
                });

            modelBuilder.Entity("Backend.Models.Tavern", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Location");

                    b.Property<string>("LodgingAvailable");

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.ToTable("Tavern");
                });

            modelBuilder.Entity("Backend.Models.Booze", b =>
                {
                    b.HasOne("Backend.Models.Tavern")
                        .WithMany("Boozes")
                        .HasForeignKey("TavernID");
                });
#pragma warning restore 612, 618
        }
    }
}
